batch_size: 8
fft_length: 384
frame_length: 256
frame_step: 160
input_shape:
- 1741
- 193
learning_rate: 0.0005
max_spectrogram_length: 1741
max_text_length: 171
model_path: Models/05_sound_to_text\202311211110
train_epochs: 1000
train_workers: 20
vocab: 'abcdefghijklmnopqrstuvwxyz''?! '
